### ISSUE TITLE
cli crashes with Error: Cannot find module './main.js'

### ISSUE THREAD

**Issue by Fak3** [Open-Attestation/open-attestation-cli#140]
version: 1.40.4
I downloaded https://github.com/Open-Attestation/open-attestation-cli/releases/download/v1.40.4/open-attestation-linux

When I launch it, I'm getting an error:
```
./open-attestation-linux 
/snapshot/project/node_modules/@digitalbazaar/http-client/index.js:1
Error: Cannot find module './main.js'
Require stack:
- /snapshot/project/node_modules/@digitalbazaar/http-client/index.js
- /snapshot/project/node_modules/jsonld/lib/documentLoaders/node.js
- /snapshot/project/node_modules/jsonld/lib/platform.js
- /snapshot/project/node_modules/jsonld/lib/jsonld.js
- /snapshot/project/node_modules/jsonld/lib/index.js
- /snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/3.0/validate/validate.js
- /snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/3.0/validate/index.js
- /snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/3.0/wrap.js
- /snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/index.js
- /snapshot/project/dist/cjs/implementations/filter/filter.js
- /snapshot/project/dist/cjs/implementations/filter/index.js
- /snapshot/project/dist/cjs/commands/filter.js
- /snapshot/project/node_modules/yargs/index.cjs
- /snapshot/project/dist/cjs/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.<anonymous> (/snapshot/project/node_modules/@digitalbazaar/http-client/index.js:8:18)
    at Module._compile (pkg/prelude/bootstrap.js:1503:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/project/node_modules/@digitalbazaar/http-client/index.js',
    '/snapshot/project/node_modules/jsonld/lib/documentLoaders/node.js',
    '/snapshot/project/node_modules/jsonld/lib/platform.js',
    '/snapshot/project/node_modules/jsonld/lib/jsonld.js',
    '/snapshot/project/node_modules/jsonld/lib/index.js',
    '/snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/3.0/validate/validate.js',
    '/snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/3.0/validate/index.js',
    '/snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/3.0/wrap.js',
    '/snapshot/project/node_modules/@govtechsg/open-attestation/dist/cjs/index.js',
    '/snapshot/project/dist/cjs/implementations/filter/filter.js',
    '/snapshot/project/dist/cjs/implementations/filter/index.js',
    '/snapshot/project/dist/cjs/commands/filter.js',
    '/snapshot/project/node_modules/yargs/index.cjs',
    '/snapshot/project/dist/cjs/index.js'
  ],
  pkg: true
}
```

**Comment by eugbyte** [comment]
## What we tried
As observed, the issue lies with the `@digitalbazaar/http-client` dependency, in particular, these lines in `node_modules/@digitalbazaar/http-client\index.js` file

```
// translate `main.js` to CommonJS
require = require('esm')(module);
module.exports = require('./main.js');
``` 

We tried including @digitalbazaar/http-client as a wholesale asset to avoid bundling and stripping of the sources, in the hopes that the dependencies can be resolved successfully:
```
"pkg": {
...
    "assets": ["node_modules/@digitalbazaar/**/*"]
  },
```

Inspecting the binary file with `DEBUG_PKG=1 ./dist/@govtechsg/open-attestation-cli`, we can see that the asset folder is successfully created
```
        node_modules
         @digitalbazaar 0  
           http-client 0  
             CHANGELOG.md 242  
             index.js 195  
             LICENSE 1498  
```
However, this solution still does not work. When we print the `module` variable in `node_modules/@digitalbazaar/http-client/index.js`, the module loader doesn't have `snapshot/node_modules/@digitalbazaar/http-client path`. 

```
paths: [
  'open-attestation-cli\\node_modules\\@digitalbazaar\\http-client\\node_modules',
  'open-attestation-cli\\node_modules\\@digitalbazaar\\node_modules',
  'open-attestation-cli\\node_modules',
  '\node_modules',
]
```

Our guess is that this could either be a problem with pkg, or a problem with digitalbazaar's compatibility with esm, as raised in this [issue](https://github.com/digitalbazaar/jsonld.js/issues/451#issuecomment-824660660).

## Solution going forward
We will try to implement our own document loader in `@govtechsg/open-attestation`, to remove the dependency on @digitalbazaar/http-client

**Comment by eugbyte** [comment]
We have created [our own jsonld library](https://www.npmjs.com/package/@govtechsg/jsonld) to remove the esm dependency that was causing issues. 
It works now.
